spring.application.name: log-processor
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    org:
      springframework: DEBUG
      springframework.beans.factory: TRACE

aws.region: ap-south-1
kinesis:
  streamName: cloudfront_logs_test
  applicationName: TEST2

writer:
  destination:
    clickhouse: false
    stdout: true
    file: false
    s3: true

# ClickHouse specific configurations when Clickhouse writer is enabled
clickhouse:
  datasource:
    user: admin
    password: admin
    url: clickhouse.com

file:
  path: "src/main/resources/output.txt"

s3:
  bucket:
    name: ls-devops-cloudfront-logs
  region: ap-south-1