apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscf-realtime-logs-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cflogs-firehose
  template:
    metadata:
      labels:
        app: cflogs-firehose
    spec:
      containers:
        - name: cflogs-firehose
          image: <YOUR_DOCKER_IMAGE_NAME>:<TAG>  # Replace with your actual Docker image name and tag
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_KINESIS_STREAM_NAME
              value: <AWS_KINESIS_STREAM_NAME>
            - name: AWS_KINESIS_APPLICATION_NAME
              value: <AWS_KINESIS_APPLICATION_NAME>
            - name: WRITER_DESTINATION_DATASOURCE
              value: "STDOUT"
            - name: AWS_REGION
              value: "ap-south-1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: kinesis-aws-credentials
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: kinesis-aws-credentials
                  key: AWS_SECRET_ACCESS_KEY
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: kinesis-aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: BASE64_ENCODED_AWS_ACCESS_KEY_ID  # Replace with your actual base64-encoded AWS Access Key ID
  AWS_SECRET_ACCESS_KEY: BASE64_ENCODED_AWS_SECRET_ACCESS_KEY  # Replace with your actual base64-encoded AWS Secret Access Key
